---

# This workflow will run Prettier on all files in the repository
# It creates a new branches with the changes. You can then create a pull request to merge the changes.
# If you need to exclude something from Prettier, you can add it to the .prettierignore file in the repository.
# Syntax of the .prettierignore file is the same as .gitignore.

name: Prettier-fix
on: [pull_request, push, workflow_dispatch]

permissions:
  contents: write

jobs:
  call-prettier-fix:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/prettierFix.yaml@main
